server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring-doc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
  pre-loading-enabled: true

spring:
  messages:
    basename: messages

  security:
    user:
      name: username
      password: passw0rd

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

